UKRIW-367 - added support for disabled Preset
EO-DataHub/eodh-fe pull request #101
Opened 2024-11-14 13:05 UTC by KatarzynaPaszko

Added support for disabled preset

2024-11-14 15:22 UTC, mlu-ssoft requested changes

2024-11-14 16:14 UTC, mlu-ssoft approved these changes

2024-11-14 16:14 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/value-node.component.tsx
> +      text={formatArea(t('MAP.ACTION_CREATOR_PANEL.WORKFLOW.NODE.AREA.DESCRIPTION'), node.value, 'km')}
use unit from settings

2024-11-15 14:14 UTC, mlu-ssoft requested changes

2024-11-15 14:14 UTC, mlu-ssoft commented on @types/i18next/resources.d.ts
> +              INSTRUCTIONS: 'Use the drawing tools to define an area of interest. Please note we cannot return results for areas greater than 1,000m2';
generate this file once again, I think this string is wrong

2024-11-15 14:14 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/value-node.component.tsx
> +  const getErrorMessage = useCallback(() => {
why not `useMemo`?

2024-11-18 07:58 UTC, KatarzynaPaszko commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/value-node.component.tsx
> +  const getErrorMessage = useCallback(() => {
updated

2024-11-18 07:58 UTC, KatarzynaPaszko commented on @types/i18next/resources.d.ts
> +              INSTRUCTIONS: 'Use the drawing tools to define an area of interest. Please note we cannot return results for areas greater than 1,000m2';
updated

2024-11-18 09:05 UTC, mlu-ssoft approved these changes

2024-11-18 09:12 UTC, merged