UKRIW-427 - onboarding tooltips
EO-DataHub/eodh-fe pull request #110
Opened 2024-11-26 08:29 UTC by KatarzynaPaszko

https://ukri-spyrosoft.atlassian.net/browse/UKRIW-427

2024-11-27 07:38 UTC, mlu-ssoft requested changes

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/area-node.component.tsx
> +    if (currentStep === onboardingSteps.DRAWING_TOOLS.step_name && node.value) {
I would move checking if it is current step into `goToNextOnboardingStep` function

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/area-node.component.tsx
> +  useEffect(() => {
why useEffect? shouldn't it by fired by events (eg user click)

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/area-node.component.tsx
> +      reference={nodeRef}
maybe `elementRef` instead of `reference`?

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/data-set/data-set-node.component.tsx
> +    if (currentStep === onboardingSteps.DATA_SET_NODE.step_name) {
this condition could be moved to `goToNextOnboardingStep`, I expect that it will always be checked

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/function-node.component.tsx
> +      nodeRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
how this `scrollIntoView` will work with the one from line 107?

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/text/text.tsx
> -  type?: 'p' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'span';
I don't think that Text element should be `div`. Those elements are used inside other elements, eg buttons, spans, it may generate wrong html semantics. if you want to element displayed as block I think better option is add styles

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
> +              // {...register('permanentHidden')}
remove

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +  const [positionOfHookElememnt, setPositionOfHookElememnt] = useState<TPosition>();
maybe just `elementPosition?`? Hook for me is eg useEffect or useMemo, so React hooks

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +  const [positionOfTheTooltip, setPositionOfTheTooltip] = useState<{
maybe `tooltipPosition`?

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +    setTooltipVisible(!!visible);
shouldn't visible be boolean type? you are using `!!positionOfTheTooltip` in conditions, so here it shouldn't be required

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +    }, 200);
why 200? why not 0 or 300? what if there will be delay on old computer and rendering will take more time than 200ms?

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +    const tooltipHook = positionOfHookElememnt;
add one line before for readibility reasons

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +    const tooltipHook = positionOfHookElememnt;
if you will define variables on the top it will be easier to read

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +        return;
you aren't returning anything, I think it should be break in that case. the same in other `switch-case` statements

2024-11-27 07:38 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +    switch (tipLocation) {
add one line before for readibility reasons

2024-11-27 09:52 UTC, KatarzynaPaszko commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/area-node.component.tsx
> +  useEffect(() => {
It should appear once this input will have value, eg. once user will finish drawing a shape on map

2024-11-27 09:59 UTC, KatarzynaPaszko commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/data-set/data-set-node.component.tsx
> +    if (currentStep === onboardingSteps.DATA_SET_NODE.step_name) {
It is there already. I just didnt remove it from here yet.

2024-11-27 10:28 UTC, KatarzynaPaszko commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +    }, 200);
hmm, I think you are right. I will increase it a bit to be on the safe side. Do you think 300 or 400 is enough?

2024-11-27 10:38 UTC, KatarzynaPaszko commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/function-node.component.tsx
> +      nodeRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
I have cleaned it up

2024-11-27 10:42 UTC, KatarzynaPaszko commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +  const [positionOfHookElememnt, setPositionOfHookElememnt] = useState<TPosition>();
I wanted to be very distinctive that it's not tooltip position, but position of an element that I hook this tooltip into, so I think its correct name

2024-11-27 10:45 UTC, KatarzynaPaszko commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +    setTooltipVisible(!!visible);
You are right, I have updated

2024-11-27 15:50 UTC, mlu-ssoft requested changes

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/area/area-node.component.tsx
> +        showOnboardingTooltip();
starting/hidding onboarding shouldn't be done in Area node. Right now logic is splitted: onboarding is started in ActionCreatorPanel and also here. it should be one place

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/function/active-node.component.tsx
> +        </div>{' '}
remove `{' '}`

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/nodes/node.component.tsx
> +          <OnboardingTooltip
this component is used by other components, eg: ValueNode, AreaNode. I think onboarding will be diplicated then

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/map/ui-search-view/src/lib/date-range-picker/date-range-picker.component.tsx
> +          <Icon name='ArrowDown' width={24} height={24} className={`${styles.icon} ${isOpen ? '' : 'rotate-180'}`} />
maybe move this into styles property?: `styles.icon(isOpen)`

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/checkbox/checkbox.tsx
> +      labelClassName,
set default values otherwise it will be parsed to undefined

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/tooltip/tooltip.tsx
> +  tooltipPosition?: React.CSSProperties;
whats the difference between position and location?

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
> +  const [currentStep, setCurrentStep] = useState<TStepName>('AREA_NODE');
it is better to pass this as a `props` in `OnboardingProvider`, eg `defaultStep`/`firstStep`. Then it won't be hardcoded in the library

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
> +        tooltip_content: t(`${translationsPath}.ADD_FUNCTION_NODE`),
why snake case? we are using camel case everywhere. Snake case is used for capitalize letters only

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
> +  const goToNextOnboardingStep = (currentTooltipStep: TStepName) => {
use `useCallback`. this is provider so any change in here will affect every child, whole app in this case

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
>    const completeOnboarding = () => {
use `useCallback`. this is provider so any change in here will affect every child, whole app in this case

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
> +  const resetOnboarding = () => {
use `useCallback`. this is provider so any change in here will affect every child, whole app in this case

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
>      if (currentStep === 'FINISH') {
add one line before for readibility reason

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
> +    if (dontShowAgain) {
add one line before for readibility reason

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/ac-workflow-onboarding.context.tsx
> +      if (currentTooltipStep === currentStep) {
if you will add return in first if then you don't need to use else and you will reduce one level of nesting

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +      // No default
I see that there is no default. This comment isn't adding any additional value. comments make sense if they are explaining something that can be understand from the code. if you would like to handle only three cases (and there is more) it is better to use if-else statement. then you don't need to add comment here.
try to answer this: in a year or two will you able to explain this comment? why it was added? why are you supported only three cases? how much time you will need to figure it out? code should be self explanatory

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +  const [positionOfTheTooltip, setPositionOfTheTooltip] = useState<{
so maybe move this into `usePosition` hook? then it will be easier to read if code if it will be in isolation

2024-11-27 15:50 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +  const [positionOfHookElememnt, setPositionOfHookElememnt] = useState<TPosition>();
as I understand this is position of `elementRef`? is so then maybe `positionElementRef`? I know that this variable doesn't sound beautifull but you can guess what it is. Hook in context of react has different meaning and I think that a lot of people will associate it with that

2024-11-28 13:59 UTC, mlu-ssoft commented on libs/shared/ui/ac-workflow-onboarding/src/lib/onboarding-tooltip/onboarding-tooltip.tsx
> +    }, 200);
I would leave it for now, I will add an comment to fix it later using Popper component from Material, it will solve problem

2024-11-28 14:21 UTC, mlu-ssoft approved these changes

2024-11-28 14:22 UTC, merged