UKRIW-125 - comparison tool component
EO-DataHub/eodh-fe pull request #113
Opened 2024-12-04 10:07 UTC by KatarzynaPaszko

Ticket: https://ukri-spyrosoft.atlassian.net/browse/UKRIW-125

2024-12-04 13:01 UTC, mlu-ssoft requested changes

2024-12-04 13:01 UTC, mlu-ssoft commented on libs/map/ui-search-view/src/lib/dynamic-tree-form/tree.component.tsx
> +            <TreeElement key={item.id} item={item} disabled={comparisonMode || disabled} />
the same situation as in DateRange component, I would merge `comparisonMode || disabled` into one `disabled` variable

2024-12-04 13:21 UTC, KatarzynaPaszko commented on libs/map/data-access-map/src/lib/store/comparison-mode/comparison-tool.store.tsx
> +  comparisonMode: boolean;
Im using it in multiple places across app. I want it to be self explanatory on first glance what it means

2024-12-05 10:46 UTC, mlu-ssoft requested changes

2024-12-05 10:46 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/store/comparison-mode/comparison-tool.store.tsx
> +  comparisonMode: boolean;
but it isn't, at least for me. what `comparisonMode` means? is it state or status? for me it looks like a state/enum. `comparisonModeEnabled` will be better name

also you can't read name without context. context should be treated as a prefix, the whole. take a look on libraries how they are doing it:
- `mui` modal, there is variable `isOpen`, not `isModalOpen` or `isMuiModalOpen`
- react hook forms: `handleSubmit`, not `handleSubmitForm`. Control, not FormControl. Only exception here is that there are two state values (formState and getFieldState), but because there are two different values there in the library
- angular material: `<mat-tab label="First">`, `label` not `matTabLabel`
- angular is wrapping native inputs with directives so you can use html, eg add `disabled` attribute to it, not `angularDisabled`/`inputDisabled`
we can have more specific names if you want, but I'm in a state that code should be readable as a story, like human language. and in human language you have context, you aren't saying `yesterday I was in a camp, in that camp there was camp shower and a lot of camp tents. there were a lot of camp people`. You would just say: `I was in a camp, there was shower and lot of tents. There were a lot of people`. Code should be from one point readable and usable for developers, but from another point should tell a story, eg should explain business purpose, language etc. It should be possible to explain what it does from business perspective by just reading the code as a sentece. I undestand that namings should be self explanatory, but I'm treating context a part of the naming. I don't have problem with that, we can add prefixes, I just want to point out my thoughs on that topic

2024-12-05 10:46 UTC, mlu-ssoft commented on libs/map/feature-timeline-analytics-dashboard/src/lib/timeline-analytics-dashboard.component.tsx
> +  const isDisabled = useMemo(() => comparisonMode || status === 'pending', [comparisonMode, status]);
maybe just `disabled`? this is the name used in other places

2024-12-05 10:46 UTC, mlu-ssoft commented on libs/map/feature-comparison-tool/src/lib/comparison-tool.component.tsx
> +  const isDisabled = useMemo(() => !(comparisonItems.firsItemId && comparisonItems.secondItemId), [comparisonItems]);
maybe just `disabled`? this is the name used in other places

2024-12-05 10:46 UTC, mlu-ssoft commented on libs/map/ui-search-view/src/lib/search-view.component.tsx
> +  const isDisabled = useMemo(() => comparisonMode || !form.formState.isValid, [comparisonMode, form.formState.isValid]);
maybe just `disabled`? this is the name used in other places

2024-12-05 10:46 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/store/comparison-mode/comparison-tool.store.tsx
> +  const toggleComparisonMode = useComparisonToolStore((state) => state.toggleComparisonMode);
you will have a lot of actions fired, add console log and look on the devtools. I would return one hook `useComparisonToolStore(state => mapValuesHere)`. otherwise use `useMemo` (but check if wont cause rerenders anyway)

2024-12-05 11:30 UTC, mlu-ssoft approved these changes

2024-12-05 11:46 UTC, merged