feat: update release process documentation
EO-DataHub/eodh-fe pull request #118
Opened 2024-12-10 22:36 UTC by mlu-ssoft

Updated documentation for release process.

Tickets:
- https://ukri-spyrosoft.atlassian.net/browse/UKRIW-430

2024-12-11 09:48 UTC, KatarzynaPaszko requested changes

2024-12-11 09:48 UTC, KatarzynaPaszko commented on docs/release-process.md
> +1. Create new `release` branch `develop` branch. Choose commit which should be released. It doesn't have to be the latest one but it should be the latest which will include tested feature.
```suggestion
1. Create new `release` branch from `develop` branch. Choose commit which should be released. It doesn't have to be the latest one but it should be the latest which will include tested feature.
```

2024-12-11 09:48 UTC, KatarzynaPaszko commented on docs/release-process.md
> +2. Create pull request from newly created branch to `master` branch.
```suggestion
2. Create pull request from newly created `release` branch to `master` branch.
```

2024-12-11 09:48 UTC, KatarzynaPaszko commented on docs/release-process.md
> +2. Create pull request from newly created branch to `master` branch.
shouldnt it be `main` ?

2024-12-11 09:48 UTC, KatarzynaPaszko commented on docs/release-process.md
> +3. Deploy newly created `release` into staging. QA team should proceed with regression.
Please describe how deploy process looks

2024-12-11 09:48 UTC, KatarzynaPaszko commented on docs/release-process.md
> +7. Merge bug into `master`. `Squash and merge` strategy should be used. Commit message should include: new version number, ticket number (in square parentheses, eg: `[UKRIW-XXX]`) and description
```suggestion
7. Merge `hotfix` branch  into `main` branch. `Squash and merge` strategy should be used. Commit message should include: new version number, ticket number (in square parentheses, eg: `[UKRIW-XXX]`) and description
```

2024-12-11 09:48 UTC, KatarzynaPaszko commented on docs/release-process.md
> +8. Merge back hotfix into `development` branch:
```suggestion
8. Merge back hotfix into `develop` branch:
```

2024-12-11 09:48 UTC, KatarzynaPaszko commented on docs/release-process.md
> +   1. Create pull request from `master` to `develop`
```suggestion
   1. Create pull request from `main` to `develop`
```

2024-12-12 13:26 UTC, KatarzynaPaszko commented on docs/release-process.md
> +4. If any bugs are found, fix them on release branch as additional commits. Commit message should be the same as after merging branch.
Why commit message should be the same? Shouldnt it say that we fix this bug?

2024-12-12 13:26 UTC, KatarzynaPaszko commented on docs/release-process.md
> +10. Generate release notes (from branch `main`).
Please describe where to put those release notes

2024-12-12 13:30 UTC, KatarzynaPaszko commented on docs/release-process.md
> +7. Merge bug into `main`. `Squash and merge` strategy should be used. Commit message should include: new version number, ticket number (in square parentheses, eg: `[UKRIW-XXX]`) and description.
```suggestion
7. Merge `hotfix` branch  into `main` branch. . `Squash and merge` strategy should be used. Commit message should include: new version number, ticket number (in square parentheses, eg: `[UKRIW-XXX]`) and description.
```

2024-12-12 13:59 UTC, mlu-ssoft commented on docs/release-process.md
> +4. If any bugs are found, fix them on release branch as additional commits. Commit message should be the same as after merging branch.
release branch will be merged without squashing so all commits will be visible. So fe if you wont put ticket name in the commit message then it will be hard to find in git history

2024-12-12 14:57 UTC, KatarzynaPaszko approved these changes

2024-12-12 16:41 UTC, merged