UKRIW-126 - comparison functionality
EO-DataHub/eodh-fe pull request #126
Opened 2024-12-13 13:36 UTC by KatarzynaPaszko

https://ukri-spyrosoft.atlassian.net/browse/UKRIW-126

2024-12-16 11:06 UTC, mlu-ssoft requested changes

2024-12-16 11:06 UTC, mlu-ssoft commented on libs/map/ui-map/src/lib/stac/stac-with-color-map.ts
> +  protected customExtent: Extent | undefined = undefined;
customExtent is not needed anymore

2024-12-16 12:32 UTC, KatarzynaPaszko commented on libs/map/feature-comparison-tool/src/lib/comparison-tool/tooltip-component/tooltip-component.styles.ts
> +  comparisonTool: `flex justify-normal items-center absolute transform top-[82px] -translate-x-1/2 left-1/2 right-1/2 p-6 z-30 bg-bright-main rounded-md shadow-action-creator w-[710px] before:content
It should not be. I have updated it

2024-12-16 12:33 UTC, KatarzynaPaszko commented on libs/map/ui-map/src/lib/comparison-mode-image-layer/comparison-mode-image-layer.component.tsx
> +      <div className='map-container'>{children}</div>
removed

2024-12-16 12:39 UTC, KatarzynaPaszko commented on libs/map/ui-map/src/lib/comparison-mode-image-layer/comparison-tool-slider/use-slider.hook.tsx
> +export const useSlider = () => {
oh, nice catch. I forgot to remove it during cleanup

2024-12-16 15:11 UTC, mlu-ssoft requested changes

2024-12-16 15:11 UTC, mlu-ssoft commented on libs/map/ui-map/src/lib/use-stac-layer-creation/use-stac-layer-creation.tsx
> +  const handleSourceReady = useCallback(
maybe `zoomToLayer`?

2024-12-16 15:11 UTC, mlu-ssoft commented on libs/map/ui-map/src/lib/use-stac-layer-creation/use-stac-layer-creation.tsx
> +  const createPublicStacLayer = useCallback(
I would refactor it a little bit:
- export only one function: `createStacLayer({ authorized: true })`
- internally there will be two functions: `createAuthorizedStacLayer` and `createUnauthrizedStacLayer`, but those functions aren't exported
- function `createStacLayer` will use `createAuthorizedStacLayer` or `createUnauthrizedStacLayer`, depends on `authorized` parameter.

the hook API will be easier to understand and use - there will be only one function which will be creating STAC layer, authorize parameter better explains what is happening there

public/private doesn't explain what it is doing, you have to go to the code to check what private/public means (calling public/private api)

2024-12-16 15:11 UTC, mlu-ssoft commented on libs/map/ui-map/src/lib/use-stac-layer-creation/use-stac-layer-creation.tsx
> +  return {
use `useMemo`

2024-12-16 15:11 UTC, mlu-ssoft commented on libs/map/ui-map/src/lib/use-stac-layer-creation/use-stac-layer-creation.tsx
> +    handleSourceReady,
I think this one doesn't have to be exported

2024-12-17 08:10 UTC, KatarzynaPaszko commented on libs/map/ui-map/src/lib/true-color-image-layer/use-stac-layer.hook.tsx
>  register(proj4);
It is needed, otherwise I get TS error on `newStacLayer`

2024-12-17 10:04 UTC, mlu-ssoft approved these changes

2024-12-17 10:04 UTC, mlu-ssoft commented on libs/map/ui-map/src/lib/comparison-mode-image-layer/use-comparison-mode-image-layer.hook.tsx
> +  const memoizedValues = useMemo(() => {
you can just return it with `useMemo`, we are doing it in othere places where hook is returing `useMemo`

2024-12-17 10:57 UTC, merged