UKRIW-141 - Create design tokens
EO-DataHub/eodh-fe pull request #14
Opened 2024-07-15 07:15 UTC by KatarzynaPaszko

2024-07-15 11:19 UTC, mlu-ssoft requested changes

2024-07-15 11:19 UTC, mlu-ssoft commented on apps/eodh-fe/src/styles/main.css
> +body {
shouldn't be `*`? double check if font will be applied to every element

2024-07-15 11:19 UTC, mlu-ssoft commented on libs/shared/theme/src/index.ts
> +export * from './lib/tokens';
do not export everything, export only things that are needed outside each library.
There are internal (inside library) and external (outside library) imports.
Not everything should be accessible outside library

2024-07-15 11:19 UTC, mlu-ssoft commented on libs/shared/theme/src/lib/tokens.js
> +    'small-medium': ['9px', { lineHeight: '13.5px', fontWeight: '500' }],
does poppins supports `400/500/600/700` font weight?

2024-07-16 10:17 UTC, KatarzynaPaszko commented on apps/eodh-fe/src/styles/main.css
> +body {
It works fine with `body` due to inheritance. 
For [various reasons](https://stackoverflow.com/questions/10041706/applying-a-single-font-to-an-entire-website-with-css) it is better to apply things to `body` instead of `*` selector

2024-07-16 10:43 UTC, KatarzynaPaszko commented on libs/shared/theme/src/lib/tokens.js
> +    'small-medium': ['9px', { lineHeight: '13.5px', fontWeight: '500' }],
I double checked, and it supports just 2 font weights, so I will update this file accordingly

2024-07-16 11:52 UTC, KatarzynaPaszko commented on libs/shared/theme/src/lib/tokens.js
> +    'small-medium': ['9px', { lineHeight: '13.5px', fontWeight: '500' }],
I ended up adding installing Poppins font in repo, as Toby requested all fin-weight support. So it will support now `400/500/600/700`

2024-07-19 14:21 UTC, mlu-ssoft requested changes

2024-07-19 14:21 UTC, mlu-ssoft commented on apps/eodh-fe/vite.config.ts
> +        join(__dirname, '..', '..'),
what this is doing?

2024-07-19 14:21 UTC, mlu-ssoft commented on apps/storybook-host/.storybook/preview.ts
> +import '@fontsource/poppins/400.css';
move those into `main.css` file

2024-07-19 14:21 UTC, mlu-ssoft commented on libs/shared/theme/src/index.ts
> +export { colors } from './lib/colors';
maybe just export `themeConfig` which will have whole configuration for theme (without splitting it into multiple variables)

2024-07-19 14:21 UTC, mlu-ssoft commented on libs/shared/theme/src/lib/colors.js
> +    // eg. bg-primary-light
remove

2024-07-19 14:21 UTC, mlu-ssoft commented on libs/shared/theme/src/lib/colors.js
> +  lightMode: {
shouldn't it be just `light`?

2024-07-19 14:21 UTC, mlu-ssoft commented on libs/shared/theme/src/lib/font-size.js
> +  // eg. text-small-semibold
remove

2024-07-19 14:21 UTC, mlu-ssoft commented on package.json
> +    "@fontsource/poppins": "^5.0.14",
remove `^` and run npm install once again

2024-07-24 07:22 UTC, KatarzynaPaszko commented on apps/eodh-fe/vite.config.ts
> +        join(__dirname, '..', '..'),
It was added once running some of Nx commands. 

As I [read in docs](https://vitejs.dev/config/server-options#server-fs-allow), the purpose of this `fs.allow `configuration is to enable Vite to access files outside of the immediate project directory. In an Nx monorepo, this is particularly useful because it allows Vite to resolve dependencies and shared code that might exist in other parts of your workspace

2024-07-24 07:31 UTC, KatarzynaPaszko commented on libs/shared/theme/src/lib/colors.js
> +  lightMode: {
I wanted it to be self explanatory, but iIf you want, I can change it

2024-07-24 08:18 UTC, mlu-ssoft requested changes

2024-07-24 08:18 UTC, mlu-ssoft commented on apps/eodh-fe/tailwind.config.js
> +        ...themeConfig.colors.light,
there should be two themes, eg dark and light
you should import one of them (instead of importing specific properties, but whole object with whole configuration)

2024-07-24 08:18 UTC, mlu-ssoft commented on libs/shared/theme/src/lib/colors.ts
> +  light: {
those should be separate themes, we should have dark/light theme with its own configuration

2024-07-24 08:18 UTC, mlu-ssoft commented on libs/shared/theme/src/lib/font-size.ts
> +  'medium-bold': ['12px', { lineHeight: '18px', fontWeight: '700' }],
shouldn't we use rem? maybe add todo to discuss it with tobi (his is on holidays right now)

2024-07-24 08:18 UTC, mlu-ssoft commented on libs/shared/theme/src/index.ts
> +const themeConfig = {
there should be two themes exported: `darkTheme`, `lightTheme`

2024-07-24 08:46 UTC, mlu-ssoft approved these changes

2024-07-24 08:51 UTC, merged