UKRI-142 - UI components
EO-DataHub/eodh-fe pull request #15
Opened 2024-07-17 07:54 UTC by KatarzynaPaszko

ticket:: https://ukri-spyrosoft.atlassian.net/browse/UKRIW-142

This PR contains: 
- Button
- Icon
- Checkbox
- RadioButton
- Toggle
- Notification
- Typography (as Text component)

Remaining components( Select, Input Text, TextArea, DropDown) will be done in following PR

To test it, run storybook and compare [with designs](https://www.figma.com/design/WDCJlvNjehFTkHVb4FSulP/UKRI-(original-bid-design)?node-id=2381-62098&t=uQLLWdWsDOEgIlak-1)

2024-07-25 15:11 UTC, mlu-ssoft requested changes

2024-07-25 15:11 UTC, mlu-ssoft commented on libs/shared/ui/design-system/src/lib/input/toggle/toggle.tsx
> +  const toggleBackgroundClasses = `w-[28px] h-[18px] bg-bright rounded-full peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 peer peer-checked:bg-blue-600 border border-1 border-pri
1. do not use values in px
2. do not use exact colors, eg ring-blue-300 or bg-blue-600 - we have design tokens for that

2024-07-25 15:11 UTC, mlu-ssoft commented on libs/shared/ui/design-system/src/lib/input/toggle/toggle.tsx
> +  const toggleCircleClasses = `absolute top-[4px] left-[4px] rounded-full h-[10px] w-[10px] transition-all  ${
do not use px

2024-07-25 15:11 UTC, mlu-ssoft commented on libs/shared/ui/design-system/src/lib/input/toggle/toggle.tsx
> +      {label && <span className='ml-3 text-sm font-medium text-gray-900'>{label}</span>}
replace `text-gray-900` with design token

2024-07-25 15:11 UTC, mlu-ssoft commented on libs/shared/ui/design-system/src/lib/notification/notification.tsx
> +  children: React.ReactNode | string;
import `ReactNode` instead `React`, maybe react will be tree shakable some day

2024-07-25 15:11 UTC, mlu-ssoft commented on package.json
> +    "clsx": "^2.1.1",
remove ^ and run npm install once again

2024-07-25 15:11 UTC, mlu-ssoft commented on tsconfig.base.json
> +      "@ukri/design-system": ["libs/shared/ui/design-system/src/index.ts"],
it should be `@ukri/shared/design-system"`

2024-07-25 15:11 UTC, mlu-ssoft commented on tsconfig.base.json
> +      "@ukri/theme": ["libs/shared/theme/src/index.ts"],
it should be `@ukri/shared/theme"`

2024-07-25 15:11 UTC, mlu-ssoft commented on tsconfig.base.json
> +      "@ukri/ui-components": ["libs/shared/ui/src/index.ts"]
is it needed?

2024-07-25 15:11 UTC, mlu-ssoft commented on libs/shared/ui/design-system/src/lib/icon/icon.tsx
> +const Icon = ({ name = 'Bolt', width = 24, height = 24 }: IIconProps) => {
icons won't be tree-shakeble, to discuss: how we should proceed with this

2024-07-25 15:11 UTC, mlu-ssoft commented on libs/shared/theme/src/lib/shadow.ts
> +  DEFAULT: '0px 4px 5px #00000033',
how this will work? how will we use it in the app?

2024-07-25 15:11 UTC, mlu-ssoft commented on libs/shared/ui/design-system/README.md
> +# design-system
to consider: I would move it to separate directory (shared/design-system instead of shared/ui/design-system)

2024-07-26 06:29 UTC, KatarzynaPaszko commented on libs/shared/ui/design-system/src/lib/button/button.stories.tsx
> +export const AllVariants = Template.bind({});
It displays in Storybook all Button variants on one page
![Screenshot 2024-07-26 at 08 28 09](https://github.com/user-attachments/assets/2861ea22-a60d-496f-ae31-9d6999659f7d)

2024-07-26 06:50 UTC, KatarzynaPaszko commented on libs/shared/ui/design-system/src/lib/icon/icon.stories.tsx
> +    expect(canvas.getByTestId('app-root')).toBeInTheDocument();
yes, it was Nx autogenerated value that I forgot to remove. It is fixed now

2024-07-26 07:10 UTC, KatarzynaPaszko commented on libs/shared/ui/design-system/src/lib/icon/icons/bolt.tsx
> +  <svg width={width} height={height} viewBox='0 0 24 24' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>
It allows the SVG element to inherit its fill color from the current text color of its parent or containing element

2024-07-26 07:15 UTC, KatarzynaPaszko commented on libs/shared/ui/design-system/src/lib/input/radio-button/radio-button.tsx
> +      <input type='radio' id={id} name={name} value={value} checked={checked} onChange={onChange} className='sr-only' />
The `value` and `checked` attributes serve different purposes:
- `value` defines the data sent to the server upon form submission for the selected radio button.
- `checked` indicates which radio button(if any) is selected by default when the page loads.

2024-07-26 07:21 UTC, KatarzynaPaszko commented on libs/shared/theme/src/lib/shadow.ts
> +  DEFAULT: '0px 4px 5px #00000033',
You just add `'shadow'` to `className`. It is used now in `Select` and `Notification` components.

2024-07-26 07:42 UTC, KatarzynaPaszko commented on libs/shared/ui/design-system/src/lib/input/checkbox/checkbox.tsx
> +const Checkbox = ({ id, initialChecked, disabled, onChange, label }: ICheckboxProps) => {
It will be needed for uniquely identifying the checkbox within the document for unit tests

2024-07-26 07:48 UTC, KatarzynaPaszko commented on libs/shared/ui/design-system/src/lib/input/checkbox/checkbox.tsx
> +        className={`w-[18px] h-[18px] flex items-center justify-center mr-2 border-1 rounded-sm transition-colors duration-200 ease-in-out ${
In tailwindCSS there is no value 4.5 (https://tailwindcss.com/docs/width), and we have design for 18px

2024-07-29 12:48 UTC, KatarzynaPaszko commented on libs/shared/ui/design-system/src/lib/input/toggle/toggle.tsx
> +  const toggleBackgroundClasses = `w-[28px] h-[18px] bg-bright rounded-full peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 peer peer-checked:bg-blue-600 border border-1 border-pri
In this case, I have to use height in px, as such value does not exist in tailwindCSS, and different value will make this component look different than on designs. 

As for colors, I have u[dated them to use theme design tokens

2024-07-29 18:40 UTC, mlu-ssoft requested changes

2024-07-29 18:40 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/checkbox/checkbox.tsx
> +      <span
create component for that, those classnames are hard to read

2024-07-29 18:40 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/checkbox/checkbox.tsx
> +          <svg
create component: `CheckedIcon` and move logic there, then here you will just use it and code will be much easier to read

2024-07-29 18:40 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/radio-button/radio-button.tsx
> +    checked && 'border-primary-main bg-bright'
those conditions are hard to read. I would create two variables and merge it using `clsx`. To consider: move styles creation to separate function (or component, eg there is a logic inside div with && - it could be separrate component).

2024-07-29 18:40 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/select/select.tsx
> +const Select = ({ options, onChange, value, placeholder = 'Select a function...' }: ISelectProps) => {
placeholder, to consider: how do we handle translations? should component itself do translations or we should pass translated message?

2024-07-29 18:40 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/select/select.tsx
> +        <svg className='fill-current h-4 w-4' xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20'>
move to separate component, I guess it is an ArrowIcon, but it is my guessing - if you name it then it will be obvious

2024-07-29 18:40 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/select/select.tsx
> +        className='block appearance-none w-full bg-white border border-bright-dark hover:border-bright-mid px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline'
to discuss: how do we wan't split logic and presentation in components, few ideas:
1. create dumb component with styles only (in this case something like that: `SelectContainer = ({ children }) => <select
        className="styles" value={value} onChange={onChange} >{children}</select>`
2. move css classes to separate files and export functions/objects. 

Reasoning:
This component has a lot of logic, it would be good if reading it we will focus only on logic, not presentation. We should split components into those with presentation and logic. Presentation can have complex styling, but in those with logic logic is the most important, so css shouldn't hide this. In the future there will be similar cases (components with logic and presentation, where we may use a lot of css classes and then component will be pretty big and hard to read)

2024-07-29 18:40 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/toggle/toggle.tsx
> +    disabled ? 'bg-neutral-light' : ' bg-primary-main'
same here (as in one of previous comments), there is logic related to css styles. we have to think how we would like to handle those cases: this component has logic in presentation (if in styles) and in itself (handleChange hook). It mixes two things: presentation and logic. We should think how to handle such cases

2024-07-29 18:40 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/toggle/toggle.tsx
> +import React, { useState } from 'react';
React import not needed

2024-07-30 09:15 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/input/select/select.tsx
> +const Select = ({ options, onChange, value, placeholder = 'Select a function...' }: ISelectProps) => {
We will create separate task for it

2024-07-30 15:13 UTC, mlu-ssoft requested changes

2024-07-30 15:13 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/icon/icons/arrow-down.tsx
> +  //   <svg width={width} height={height} viewBox='0 0 24 24' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>
remove

2024-07-30 15:13 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/icon/icons/arrow-down.tsx
> +  <svg width={width} height={height} viewBox='0 0 12 7' fill='black' xmlns='http://www.w3.org/2000/svg'>
chagne fill to `currentColor`

2024-07-30 15:13 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/checkbox/checkbox.styles.tsx
> +  if (disabled) return `${checkboxStyles.span.base} ${checkboxStyles.span.disabled}`;
1. add braces for if
2. add eslint rule for that: https://eslint.org/docs/latest/rules/curly

2024-07-30 15:13 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/checkbox/checkbox.styles.tsx
> +  if (isChecked) return `${checkboxStyles.span.base} ${checkboxStyles.span.checked}`;
1. add braces for if
2. add eslint rule for that: https://eslint.org/docs/latest/rules/curly

2024-07-31 09:23 UTC, mlu-ssoft approved these changes

2024-07-31 09:26 UTC, merged