UKRIW-142 -  UI components part2
EO-DataHub/eodh-fe pull request #22
Opened 2024-08-02 07:23 UTC by KatarzynaPaszko

ticket:: https://ukri-spyrosoft.atlassian.net/browse/UKRIW-142

This PR contains:

- Select, 
- Input Text, 
- TextArea

To test it, run storybook and compare [with designs](https://www.figma.com/design/WDCJlvNjehFTkHVb4FSulP/UKRI-(original-bid-design)?node-id=2381-62098&t=uQLLWdWsDOEgIlak-1)

2024-08-05 10:17 UTC, mlu-ssoft requested changes

2024-08-05 10:17 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/select/select.tsx
> +          onClick={() => setIsOpen(!isOpen)}
I would move this to `handleClose` function or something. It is hard to read if the logic is hidden deeply in html tree

2024-08-05 10:17 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/textarea/textarea.tsx
> +import textareaStyles from './textarea.styles'; // Adjust the path as needed
what this comment means?

2024-08-05 10:17 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/textarea/textarea.tsx
> +    setText(e.target.value);
won't it cause performance issues?

2024-08-05 10:17 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/textarea/textarea.tsx
> +          {text.length}/{maxLength} characters
use translation keys

2024-08-07 13:53 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/select/select.tsx
> +export const Select = ({ options, onChange, placeholder = 'Select an option' }: ISelectProps) => {
Your PR with translations is not merged yet, so can't use translation function

2024-08-07 14:23 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/input/text-input/text-input.tsx
> +  placeholder = 'Start typing...',
Will do once multi language support PR will be merged into develop

2024-08-07 14:24 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/textarea/textarea.tsx
> +import textareaStyles from './textarea.styles'; // Adjust the path as needed
removed

2024-08-07 14:24 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/textarea/textarea.tsx
> +          {text.length}/{maxLength} characters
Will do once multi language support PR will be merged into develop

2024-08-08 07:39 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/textarea/textarea.tsx
> +    setText(e.target.value);
I will add useCallback

2024-08-13 13:59 UTC, mlu-ssoft approved these changes

2024-08-14 10:02 UTC, merged