UKRIW-150 login spike
EO-DataHub/eodh-fe pull request #25
Opened 2024-08-09 13:30 UTC by KatarzynaPaszko

POC for authorization spike ticket: https://ukri-spyrosoft.atlassian.net/browse/UKRIW-150

2024-08-12 09:37 UTC, mlu-ssoft requested changes

2024-08-12 09:37 UTC, mlu-ssoft commented on apps/eodh-fe/.env
> +VITE_BASE_URL=http://localhost:4200
remove, this file shouldn't be in the repo

2024-08-12 09:37 UTC, mlu-ssoft commented on apps/eodh-fe/index.html
> +        script-src  'self' https://test.eodatahub.org.uk;
1. why we need this?
2. it shouldn't be hardcoded, we can have different environments

2024-08-12 09:37 UTC, mlu-ssoft commented on apps/storybook-host/.env
> +VITE_BASE_URL=http://localhost:4200
remove, this file shouldn't be in the repo

2024-08-12 09:37 UTC, mlu-ssoft commented on jest.config.ts
> +import { getJestProjects } from '@nx/jest';
we use vitest for tests, change it

2024-08-12 09:37 UTC, mlu-ssoft commented on jest.preset.js
> +const nxPreset = require('@nx/jest/preset').default;
same here, use vitest

2024-08-12 09:37 UTC, mlu-ssoft commented on libs/authorization/data-access/package.json
> +{
don't create buildable libraries, we won't publish it to npm

2024-08-12 09:37 UTC, mlu-ssoft commented on libs/authorization/data-access/src/lib/keycloak.ts
> +  url: 'https://test.eodatahub.org.uk/keycloak',
those settings should be in .env file

2024-08-12 09:37 UTC, mlu-ssoft commented on libs/authorization/ui/package.json
> +{
remove, we don't need buildable libraries

2024-08-12 09:37 UTC, mlu-ssoft commented on libs/authorization/ui/src/lib/authorization.tsx
> +  const currentUrl = window.location.href;
shouldn't you save url in localStorage and then use it?

2024-08-12 09:37 UTC, mlu-ssoft commented on libs/authorization/ui/src/lib/authorization.tsx
> +    <div className={clsx('flex items-center', className)}>
we don't need ui library for authorisation, move it to default layout

2024-08-12 09:37 UTC, mlu-ssoft commented on package.json
> +    "@nx/jest": "16.10.0",
remove jest

2024-08-12 09:37 UTC, mlu-ssoft commented on libs/authorization/data-access/.eslintrc.json
> +{
move all code from `authorisation/data-access` into `shared/utils/auth`. If we leave this in authorisation then we won't be able to use it in other places (eg. in map `domain`)

2024-08-12 09:37 UTC, mlu-ssoft commented on libs/authorization/data-access/project.json
> +  "tags": ["type:data-access"],
scope missing

2024-08-12 09:37 UTC, mlu-ssoft commented on nx.json
> +    "@nx/js:tsc": {
why this was added? do we use tsc executor somewhere?

2024-08-13 10:24 UTC, KatarzynaPaszko commented on apps/eodh-fe/index.html
> +        script-src  'self' https://test.eodatahub.org.uk;
It was for POC testing purposes. I will remove it

2024-08-13 13:59 UTC, KatarzynaPaszko commented on libs/authorization/ui/src/lib/authorization.tsx
> +  const currentUrl = window.location.href;
as discussed in priv, not needed

2024-08-13 13:59 UTC, KatarzynaPaszko commented on nx.json
> +    "@nx/js:tsc": {
removed

2024-08-27 13:09 UTC, mlu-ssoft approved these changes

2024-08-27 13:29 UTC, merged