UKRIW-251 - Slider
EO-DataHub/eodh-fe pull request #29
Opened 2024-08-16 12:22 UTC by KatarzynaPaszko

https://ukri-spyrosoft.atlassian.net/browse/UKRIW-251

2024-08-19 08:35 UTC, mlu-ssoft requested changes

2024-08-19 08:35 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/slider/slider.stories.tsx
> +    onChange: (value: number) => console.log(value),
remove, do we need console log in storybook?

2024-08-19 08:35 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/slider/slider.css
> +.sliderRangeInput {
why css not tailwind?

2024-08-19 08:35 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/slider/slider.tsx
> +        onChange={(e) => handleChange(e)}
it can be: `onChange={handleChange}`

2024-08-19 08:35 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/slider/slider.tsx
> +  const getBackgroundStyle = useMemo(() => {
can you use tailwind classes for this?

2024-08-19 08:35 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/slider/slider.tsx
> +  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
add useCallback

2024-08-20 18:58 UTC, mlu-ssoft requested changes

2024-08-20 18:58 UTC, mlu-ssoft commented on libs/shared/theme/src/lib/ligh-theme.config.ts
> +    light: '#BED4FF',
why change in light theme?

2024-08-20 18:58 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/slider/slider.css
> +.designSystemSliderRangeInput {
use BEM naming, it will explain reasoning for long name (designSystem prefix)

2024-08-21 06:54 UTC, KatarzynaPaszko commented on libs/shared/theme/src/lib/ligh-theme.config.ts
> +    light: '#BED4FF',
It was updated in design system
<img width="420" alt="Screenshot 2024-08-21 at 08 54 11" src="https://github.com/user-attachments/assets/0f7cc0ba-ed0c-4946-969c-4e8fbe639f7f">

2024-08-21 15:03 UTC, mlu-ssoft approved these changes

2024-08-21 19:04 UTC, merged