UKRIW-18 - data range in search module
EO-DataHub/eodh-fe pull request #32
Opened 2024-08-27 11:07 UTC by KatarzynaPaszko

Ticket: https://ukri-spyrosoft.atlassian.net/jira/software/projects/UKRIW/boards/1?assignee=5e4e41887ece1a0c9992c39a&selectedIssue=UKRIW-17

2024-08-27 15:06 UTC, mlu-ssoft requested changes

2024-08-27 15:06 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/date-range-picker/date-range-picker.component.tsx
> +export const DateRangePicker = () => {
pass min/max date as parameter

2024-08-27 15:06 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/date-range-picker/date-range-picker.component.tsx
> +  const oneMonthAgo = new Date();
move date callculation into hook

2024-08-27 15:06 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/date-range-picker/date-range-picker.component.tsx
> +      if (toDate && date > toDate) {
move to separate compare function. you are assuming that dates are numbers, but it doesn't have be like that

2024-08-27 15:06 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/date-range-picker/date-range-picker.component.tsx
> +      if (fromDate && date < fromDate) {
same here, move to function

2024-08-27 15:06 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/date-range-picker/date-range-picker.component.tsx
> +  const toggleOpen = () => {
add useCallback

2024-08-27 15:06 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/search-panel.component.tsx
> +        <Button text='Search' className='w-full flex justify-center mt-0' size='large' />
add translation key for `Seach`

2024-08-27 15:06 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/input/date-input/date-input.tsx
> +    <div className=''>
remove

2024-08-27 16:22 UTC, mlu-ssoft requested changes

2024-08-27 16:22 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/date-range-picker/date-range-picker.component.tsx
> +const isDateAfterToDate = (date: string, toDate?: string) => {
maybe just `isDateAfter(date1, date2)` (or name date1/date2 params differently)?

2024-08-27 16:22 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/date-range-picker/date-range-picker.component.tsx
> +const isDateBeforeFromDate = (date: string, fromDate?: string) => {
maybe just `isDateBefore(date1, date2)` (or name date1/date2 params differently)?

2024-08-27 16:22 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/date-range-picker/dates-calculations.hook.tsx
> +const useDateCalculations = () => {
I would split this into two functions:
- useDate which will return two dates: today, oneMonthAgo|
- formatDate which will format date

2024-08-27 16:22 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/search-panel.component.tsx
> +        <DateRangePicker maxDate={formattedToday} minDate={minDate} />
why minDate isn't formatted as formattedToday date?

2024-08-28 06:28 UTC, KatarzynaPaszko commented on libs/map/ui-search-panel/src/lib/date-range-picker/date-range-picker.component.tsx
> +const isDateAfterToDate = (date: string, toDate?: string) => {
hmm, I think now name of the function and name of it parameters explains very good what this function does. 
is**Date**After`ToDate` = (**date**: string, `toDate`?: string)

If I will update it as per your suggestion, then you need to go back to function and analyze it which parameter should go first and which one should be second.

2024-08-28 06:36 UTC, KatarzynaPaszko commented on libs/map/ui-search-panel/src/lib/date-range-picker/date-range-picker.component.tsx
> +const isDateBeforeFromDate = (date: string, fromDate?: string) => {
Same as above

2024-08-28 06:40 UTC, KatarzynaPaszko commented on libs/map/ui-search-panel/src/lib/search-panel.component.tsx
> +        <DateRangePicker maxDate={formattedToday} minDate={minDate} />
minDate is passed as a parameter. It is formatted already

2024-08-28 06:42 UTC, KatarzynaPaszko commented on libs/map/ui-search-panel/src/lib/date-range-picker/dates-calculations.hook.tsx
> +const useDateCalculations = () => {
Then we will need to import 2 hooks in every places, instead of one. And there is no case that we will use one, but not the other

2024-08-28 07:16 UTC, mlu-ssoft commented on libs/map/ui-search-panel/src/lib/date-range-picker/dates-calculations.hook.tsx
> +const useDateCalculations = () => {
add then todo to split this function in the future. we will need one function for date formatting

2024-08-28 07:16 UTC, mlu-ssoft approved these changes

2024-08-28 11:13 UTC, mlu-ssoft approved these changes

2024-08-28 12:00 UTC, merged