UKRIW-335 - display results on left panel
EO-DataHub/eodh-fe pull request #34
Opened 2024-08-30 11:41 UTC by KatarzynaPaszko

Ticket Acs: https://ukri-spyrosoft.atlassian.net/browse/UKRIW-62

2024-08-30 11:53 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/icon/icons/satellite-alt.tsx
> +  <svg width={width} height={height} viewBox='0 0 48 48' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>
SateliteAlt is 48x48 by Toby request

2024-08-30 14:47 UTC, mlu-ssoft requested changes

2024-08-30 14:47 UTC, mlu-ssoft commented on apps/eodh-fe/public/assets/i18n/en.json
> +        "MESSAGE": " Please refine your search criteria. Try a broader date range, adjust Data Set settings or consider choosing multiple Data Sets."
remove empty space at beggining of the translation

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-list/results-list.component.tsx
> +          // actual functions to be added in future
add todo

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-list/results-list.component.tsx
> +  const handleThumbnailSelect = (index: number) => {
add useCallback

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-list/results-list.stories.tsx
> +  imageUrl: '/assets/images/imageSample2.png', // image is added in the assets folder in storybook-host
maybe instead of adding comment use proper variable name? eg: `const imageUrlStoredInPublicAssetsInStorybookHost = '...'`

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-panel.component.tsx
> +  if (props.status === 'success') {
you can use one if condition

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-panel.component.tsx
> +  if (props.status === 'error') {
consider using `switch-case`

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-panel.component.tsx
> +  onReturn: () => void;
maybe `onBack`?

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-panel.stories.tsx
> +  imageUrl: '/assets/images/imageSample2.png', // image is added in the assets folder in storybook-host
maybe instead of adding comment use proper variable name? eg: `const imageUrlStoredInPublicAssetsInStorybookHost = '...'`

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-panel.stories.tsx
> +    onReturn: () => {
you can add eslint-ignore rule for empty function in this case

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/api-error/api-error.tsx
> +export const ApiError = ({ iconName, title, message, buttonText, buttonOnClick }: IApiErrorProps) => {
maybe just `Error`?

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/icon/icons/satellite-alt.tsx
> +  <svg width={width} height={height} viewBox='0 0 48 48' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>
can we create component which will have 24x24 and make it bigger in places where it is needed? I would prefer to have all icons in the same size in Design System

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +// Added for now, to be rempved in the foture once we will work on comparison functionality
add todo. if something should be done in the future use todo. it will be easier to search in the project, eg search for // todo

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +    if (isAddedForComparison === false && onAddToCompare) {
it can be simplified: `if (!isAddedForComparison && onAddToCompare) {`

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +    } else if (isAddedForComparison === true && onRemoveFromCompare) {
it can bi simplified: `else if (isAddedForComparison && onRemoveFromCompare) {`

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +      setIsAddedForComparison(false);
why this is invoked only if there is `onRemoveFromCompare` callback?

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +      setIsAddedForComparison(true);
why this is invoked only if there is `onAddToCompare` callback?

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +  addedForComparison = false,
this name suggest for what it will be used. This component should be more generic. Maybe `showCompareButton`?

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +  onAddToCompare: () => void;
you could use one callback: `onCompareToggle` or just `onCompare` with `true/false` or `mode: add/remove` as a parameter

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/api-error/api-error.tsx
> +  buttonOnClick?: () => void;
maybe just `onClick`?

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/api-error/api-error.tsx
> +  buttonText?: string;
1. type should be ParseKeys from i18n
2. maybe `actionText`? there is title and message, those don't suggest where are used, eg there is no divTitle or divMessage

2024-08-30 14:47 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/api-error/api-error.stories.tsx
> +    buttonOnClick: () => {
you could add eslint disable rule

2024-09-02 10:00 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/icon/icons/satellite-alt.tsx
> +  <svg width={width} height={height} viewBox='0 0 48 48' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>
I will update height and width, but I can't mess up with viewBox, coz then icon is broken.

2024-09-02 10:16 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +      setIsAddedForComparison(false);
because we want to make sure that it is not just visual change on Thumbnail/ResultItem. We want to make sure that this Item is indeed being proces by function and added for comparison.

2024-09-02 10:16 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +      setIsAddedForComparison(true);
Same as above

2024-09-02 11:21 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/api-error/api-error.tsx
> +  buttonOnClick?: () => void;
updated to ctaOnClick

2024-09-02 11:21 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/api-error/api-error.tsx
> +  buttonText?: string;
updated to ctaText

2024-09-02 12:23 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/icon/icons/satellite-alt.tsx
> +  <svg width={width} height={height} viewBox='0 0 48 48' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>
you can ask Tobi to add this icon to icons and then download it

2024-09-02 13:07 UTC, mlu-ssoft requested changes

2024-09-03 08:06 UTC, mlu-ssoft requested changes

2024-09-03 08:06 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-list/results-list.component.tsx
> +    <div className='thumbnail-list'>
why css class is here?

2024-09-03 08:06 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-list/results-list.component.tsx
> +  const [selectedThumbnailIndex, setSelectedThumbnailIndex] = useState<number | null>(null);
consider using ID, I think each result should have ID property
index may change (while rerendering) so I think we should at least reset index then results property changes

2024-09-03 08:06 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-panel.component.tsx
> +    case 'success':
add braces, it is easly to miss that there is return condition below

2024-09-03 08:06 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-panel.component.tsx
> +    case 'error':
add braces

2024-09-03 08:06 UTC, mlu-ssoft commented on libs/map/ui-results-panel/src/lib/results-panel.component.tsx
> +    default:
add braces

2024-09-03 08:06 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/thumbnail/thumbnail.tsx
> +  onAddToCompare: () => void;
I would create two types for IThumbnailProps, one without onAddToCompare and onRemoveFromCompare functions and second one with those functions. Then it will be clear that you have to pass two of those functions (or none of them)

2024-09-03 10:26 UTC, KatarzynaPaszko commented on libs/map/ui-results-panel/src/lib/results-list/results-list.component.tsx
> +    <div className='thumbnail-list'>
I was testing something, and forgot to remove. Its removed now

2024-09-03 12:11 UTC, mlu-ssoft approved these changes

2024-09-03 12:45 UTC, merged