UKRIW-80 -  action creator workflow nodes component
EO-DataHub/eodh-fe pull request #59
Opened 2024-09-23 07:49 UTC by KatarzynaPaszko

2024-09-23 11:26 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/icon/icons/action-creator-arrow.tsx
> +      fill='#4483FF'
I added color for now, as this is temporary arrow that will be replaced by ReactFlow framework arrows

2024-09-24 08:09 UTC, mlu-ssoft requested changes

2024-09-24 08:09 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/pseudo-input.component.tsx
> +export const PseudoInput: React.FC<IPseudoInputProps> = ({ value, onChange, className, iconName = 'Satellite' }) => {
this should be normal input. In the future we will use react hook form to validate data in Workflow tab

2024-09-24 08:09 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/icon/icons/action-creator-arrow.tsx
> +      fill='#4483FF'
ok

2024-09-24 08:09 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/select/select.tsx
>  }: ISelectProps) => {
This select should be not connected component (without internal state). This way we will be able to use it with react hook forms. If you need component with state then create two components - one basic, second one with state (eg. ConnectedSelect or something like that)

2024-09-24 08:09 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/function-input.component.tsx
> +  onChange: (value: string) => void;
I would this optional

2024-09-24 08:09 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/workflow.component.tsx
> +        <Node {...args} type='area'>
I would create new component for each type: AreaComponent, DataSetsComponent, DateRangeComponent, FunctionComponent and here just display those components. Then each component will have its own logic

2024-09-24 08:09 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/workflow.component.tsx
> +          {showInputs && <PseudoInput iconName='Polygon' value={'sample aoi'} />}
can be just string, same in other `PseudoInput` components

2024-09-25 07:56 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/select/select.tsx
>  }: ISelectProps) => {
added comment to do in another ticket

2024-09-25 09:28 UTC, mlu-ssoft requested changes

2024-09-25 09:28 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/workflow/node-select.component.tsx
> +  const handleChange = (value?: string | null) => {
add useCallback

2024-09-25 09:28 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/select/select.tsx
> +      if (ref.current && !(ref.current as Node).contains(event.target as Node)) {
maybe there should be different type for useRef?

2024-09-25 09:46 UTC, mlu-ssoft approved these changes

2024-09-25 09:48 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/select/select.tsx
> +      if (ref.current && !(ref.current as Node).contains(event.target as Node)) {
Will be done in another ticket

2024-09-25 09:48 UTC, merged