UKRIW-358 - cloud coverage bug fix
EO-DataHub/eodh-fe pull request #66
Opened 2024-09-27 13:55 UTC by KatarzynaPaszko

https://ukri-spyrosoft.atlassian.net/browse/UKRIW-358

Fixed bug: Once cloud coverage is 0, Cloud coverage metadata is displayed wrongly

2024-09-30 08:01 UTC, mlu-ssoft requested changes

2024-09-30 08:01 UTC, mlu-ssoft commented on libs/shared/design-system/src/lib/result-item/result-item.tsx
> +    return typeof cloudCoverage === 'number' ? `${cloudCoverage.toFixed(2)}%` : cloudCoverage;
use `isNumber` from lodash. Checking if it is number is more complex

2024-09-30 12:21 UTC, KatarzynaPaszko commented on libs/shared/design-system/src/lib/result-item/result-item.tsx
> +    return typeof cloudCoverage === 'number' ? `${cloudCoverage.toFixed(2)}%` : cloudCoverage;
done

2024-10-01 07:48 UTC, mlu-ssoft approved these changes

2024-10-01 07:59 UTC, merged