UKRIW-398 - displaying Presets functions
EO-DataHub/eodh-fe pull request #74
Opened 2024-10-11 15:15 UTC by KatarzynaPaszko

https://ukri-spyrosoft.atlassian.net/browse/UKRIW-398

This pull request introduces several changes to improve the handling of presets, enhance the HTTP client configuration, and update the environment configuration. The most important changes include adding a new internal API URL, implementing a new preset schema and query, and refactoring various components to support these updates.

### Environment Configuration Updates:
* Added `VITE_INTERNAL_API_URL` to `.env`.
* Updated `interface IEnvConfig` to include `internalApiUrl`.
* Modified `getEnvConfig` to handle `VITE_INTERNAL_API_URL`.

### HTTP Client Configuration:
* Updated `initHttpClient` function to support multiple base URLs by adding an `id` parameter.

### Preset Handling:
* Introduced `presetsSchema` and `TPresets` type.
* Implemented `useGetPresets` query and used it in `Presets` component.

### Component Refactoring:
* Updated`Footer` component to handle conditional rendering based on the active tab.
* Updated `Content` component to include the new `Footer`.

### Other Changes:
* Updated `img-src` directive in `apps/eodh-fe/index.html` to include `data:`.
* Added error handling messages for presets in `apps/eodh-fe/public/assets/i18n/en.json`.

2024-10-14 10:29 UTC, mlu-ssoft requested changes

2024-10-14 10:29 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/lib/axios.ts
> +export const getHttpClient = (id = 'baseUrl') => {
this should be generic, it shouldn't know anything about different implementations (library should be configurable, but it shouldn't know nothing about specific implementations). it means that 'baseUrl' default parameter value shouldn't be here, it should came from configuration.

2024-10-14 10:29 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/lib/axios.ts
> +  instances[id] = instance;
what if instance already exists?

2024-10-14 10:29 UTC, mlu-ssoft commented on scripts/create-config-file.js
> +  internalApiUrl: getVariableValue(process.env.VITE_INTERNAL_API_URL),
move this to `httpClient` config

2024-10-14 10:29 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/lib/model.ts
> +  id: string;
it should be array with available urls, eg `proxyConfig: { [key: string]: string }`

2024-10-14 10:29 UTC, mlu-ssoft commented on apps/eodh-fe/index.html
> +        img-src     'self' https://tile.openstreetmap.org https://sentinel-cogs.s3.us-west-2.amazonaws.com data:;
data shouldn't be allowed from one domain only?

2024-10-14 10:29 UTC, mlu-ssoft commented on apps/eodh-fe/.env.example
> +VITE_INTERNAL_API_URL=http://example.com
I would use different name, maybe?:
- STAC or TPZ/TELESPAZIO - for telespazio API
- EOPRO - for our API

2024-10-15 15:03 UTC, KatarzynaPaszko commented on apps/eodh-fe/index.html
> +        img-src     'self' https://tile.openstreetmap.org https://sentinel-cogs.s3.us-west-2.amazonaws.com data:;
this was added so we can display images base64

2024-10-15 15:34 UTC, mlu-ssoft requested changes

2024-10-15 15:34 UTC, mlu-ssoft commented on apps/eodh-fe/.env.example
> +VITE_INTERNAL_API_URL=http://example.com
not fixed, change also names here

2024-10-15 15:34 UTC, mlu-ssoft commented on apps/eodh-fe/index.html
> +        img-src     'self' https://tile.openstreetmap.org https://sentinel-cogs.s3.us-west-2.amazonaws.com data:;
yep, I know, but shouldn't be allow using data from only one domain? I don't know if it is possible, but if it is it will be better from security point of view

2024-10-15 15:34 UTC, mlu-ssoft commented on apps/eodh-fe/src/env.config.ts
> +const eodhProUrl = () => {
maybe `getEodhProUrl`? this is function, not constant

2024-10-15 15:34 UTC, mlu-ssoft commented on apps/eodh-fe/src/env.config.ts
> +  if (importedUrl) {
add one line before for better readibility

2024-10-15 15:34 UTC, mlu-ssoft commented on apps/eodh-fe/src/env.config.ts
> +  return '';
add one line before for better readibility

2024-10-15 15:34 UTC, mlu-ssoft commented on apps/storybook-host/.storybook/config/env.config.ts
> +  if (importedUrl) {
add one line before for better readibility

2024-10-15 15:34 UTC, mlu-ssoft commented on apps/storybook-host/.storybook/config/env.config.ts
> +  return '';
add one line before for better readibility

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/presets/presets.model.ts
> +const functionSchema = z.object({
endpoint with this schema returns both presets and functions. we should have one react query hook which will return cached data and two additional hooks for presets and functions (those should filter by preset field). I think we should have different schema (internal) for presets and functions. In preset we don't need to have inputs field, only name, description etc will be important

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/presets/response-formatter.ts
> +  response.functions.forEach((func) => {
you can do this using zod

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/presets/presets.model.ts
> +});
I would add map this type into internal one, remove `thumbnail_b64` and create `image`/`imageUrl` property instead

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/presets/preset.component.tsx
> +  base64String: string;
is it still `base64String`? You added data attribute in data-access, I think `imageUrl` is right now better name

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/presets/preset.component.tsx
> +export const Preset = ({ base64String, title, description, onLoadPresetClick, className }: IResultItemProps) => {
same here, I think `imageUrl` is better than `base64String`

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/lib/axios.ts
> +  return instance;
this fn should be void, remove

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/lib/proxy.interceptor.ts
> +    const arrayOfUrls = Object.entries(proxyConfig)
add one empty line before for better readibility

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/lib/proxy.interceptor.ts
> +    if (!proxyConfig || Object.keys(proxyConfig).length === 0) {
it can be simplified: `!Object.keys(proxyConfig).length`

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/lib/proxy.interceptor.ts
> +    return { ...request, url: arrayOfUrls.length > 0 ? arrayOfUrls.pop() : request.url };
it can be simplified: `arrayOfUrls.length ? arrayOfUrls.pop() : request.url`

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/index.ts
> +export type { IHttpClientConfig, IHttpInterceptor, IHttpRequest } from './lib/model';
is it used somewhere, do we need to export this? I couldn't find imports for those types

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/lib/proxy.interceptor.ts
> +    const arrayOfUrls = Object.entries(proxyConfig)
it can be simplified:
`Object.values(proxyConfig).map((key) => request.url?.startsWith(key) ? request.url?.replace(key, proxyConfig[key]) : undefined).filter((url) => !!url);`

2024-10-15 15:34 UTC, mlu-ssoft commented on libs/shared/utils/react-query/src/lib/proxy.interceptor.ts
> +    const arrayOfUrls = Object.entries(proxyConfig)
this still don't check if there are trailing slashes:
- I can add multiple trailing slashes in the configuration, eg: `https://test.eodatahub.org.uk//////`
- I'm not forced to use types. I can forgot about it and pass url like that: `/////example-url`
library should prevent such situations

2024-10-15 15:34 UTC, mlu-ssoft commented on apps/eodh-fe/src/env.config.ts
> +  if (importedUrl) {
what if `importedUrl` will have trailing slash, eg `https://test.eodatahub.org.uk////`? if you are combining two strings you should make sure that there won't be any unnecessary slashes

2024-10-15 15:55 UTC, KatarzynaPaszko commented on libs/shared/utils/react-query/src/lib/proxy.interceptor.ts
> +    const arrayOfUrls = Object.entries(proxyConfig)
> it can be simplified: `Object.values(proxyConfig).map((key) => request.url?.startsWith(key) ? request.url?.replace(key, proxyConfig[key]) : undefined).filter((url) => !!url);`

It wont work with `Object.values`, thats why I have updated it with `Object.entries`

2024-10-16 07:47 UTC, KatarzynaPaszko commented on apps/eodh-fe/index.html
> +        img-src     'self' https://tile.openstreetmap.org https://sentinel-cogs.s3.us-west-2.amazonaws.com data:;
I tried to find other way, but Im keep on getting CSP error. Do you know some other way to overcome this issue?

2024-10-16 15:25 UTC, mlu-ssoft approved these changes

2024-10-16 15:27 UTC, merged