UKRIW-410
EO-DataHub/eodh-fe pull request #76
Opened 2024-10-18 14:51 UTC by KatarzynaPaszko

https://ukri-spyrosoft.atlassian.net/browse/UKRIW-410

2024-10-21 09:17 UTC, mlu-ssoft requested changes

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/history/history.model.ts
> +      return 'FAILED';
1. do we need to use native BE statuses somewhere?
2. how do we mark item as ready on websockets?
3. how and where mapping on websockets will be done?

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/history/history.model.ts
> +    .transform((dateString) => {
I wouldn't map it here. It may be like that in other places we will need full date. In theory this endpoint may be used by multiple views. This mapping (into date and hour) looks like very specific to one view. I would do mapping in this view then (instead of doing it globally)

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/history/history.model.ts
> +  finished_at: z.union([z.string().datetime(), z.null(), z.undefined()]),
we are using camelCase, I would mapp `finished_at` into `finishedAt`. same with other fields

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/history/history.query.tsx
> +const history = async ({
maybe `getHistoryResults`?

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/history-tile/history-tile.component.tsx
> +            content={`ID: ${truncateString(workflowId, 25)}`}
add it into translations. maybe in different language `ID` will be something different

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/history-tile/history-tile.component.tsx
> +            onClick={selected ? onHideResult : onViewResult}
maybe create two buttons? SelectedButton and ViewResultsButton? There is logic repeated twice (in text and in onClick)

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/sort-filter/sort-filter.component.tsx
> +export const SortFilter = React.memo(({ onSortChange, sortKey, className }: ISortFilterProps) => {
you can import `memo` from React lib directly

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/sort-filter/sort-filter.component.tsx
> +    document.addEventListener('mousedown', handleClickOutside);
don't we have dropdown component with clicking outside logic already? I prefer do not use native browser features in multiple places if not needed. eg if at some point we would like to create mobile app then it will be hard to find all those places

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/sort-filter/sort-filter.component.tsx
> +  const handleSortSelection = (order: TSortOrder) => {
add useCallback

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/sort-filter/sort-filter.component.tsx
> +  const toggleDropdown = () => setIsOpen(!isOpen);
add useCallback

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/use-history-data.hook.ts
> +  const loadMore = () => {
add useCallback

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/use-history-data.hook.ts
> +    if (data && !isLoading && !isFetching) {
I think you could use `isPending` which is the same as `isLoading || isFetching`

2024-10-21 09:17 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/use-history-data.hook.ts
> +      const newResults = data.results.filter(
this state right now is locall. how do we mark item as ready when we will have websockets?

2024-10-21 09:22 UTC, KatarzynaPaszko commented on libs/map/data-access-map/src/lib/history/history.model.ts
> +      return 'FAILED';
1. - we just need to know if it is failed or no to display red tag, thats why I map all 3 to one here
2. , 3.  - it was agreed that it will be done in this ticket  https://ukri-spyrosoft.atlassian.net/browse/UKRIW-117

2024-10-21 09:26 UTC, KatarzynaPaszko commented on libs/map/feature-action-creator-panel/src/lib/content/history/sort-filter/sort-filter.component.tsx
> +    document.addEventListener('mousedown', handleClickOutside);
This is totally different component with different logic and styling than dropdown that we have in DesignSystem

2024-10-21 09:27 UTC, KatarzynaPaszko commented on libs/map/feature-action-creator-panel/src/lib/content/history/use-history-data.hook.ts
> +      const newResults = data.results.filter(
This will need to be done in https://ukri-spyrosoft.atlassian.net/browse/UKRIW-117

2024-10-21 09:57 UTC, KatarzynaPaszko commented on libs/map/data-access-map/src/lib/history/history.query.tsx
> +const history = async ({
With presets and search we just used one word. Do you want to change convention everywhere?
<img width="579" alt="Screenshot 2024-10-21 at 11 55 52" src="https://github.com/user-attachments/assets/31947902-de40-4c9b-b7d4-cd45e504b89d">
<img width="504" alt="Screenshot 2024-10-21 at 11 56 09" src="https://github.com/user-attachments/assets/99a7466e-aa8b-49cd-8277-5f22d032b5aa">

2024-10-21 10:16 UTC, KatarzynaPaszko commented on libs/map/feature-action-creator-panel/src/lib/content/history/use-history-data.hook.ts
> +    if (data && !isLoading && !isFetching) {
`IsPending` was introduced to replace `isLoading`, but not `isFetching`: https://tanstack.com/query/v5/docs/framework/react/guides/migrating-to-v5

I will replace `isLoading` with `isPending`

2024-10-21 10:38 UTC, mlu-ssoft requested changes

2024-10-21 10:38 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/history-tile/history-tile.component.tsx
> +            onClick={selected ? onHideResult : onViewResult}
yep, and it is logic, so not only text but also onClick behaviour changed.
selected condition is repeated twice, so you can add:
- two buttons and display only one of them at a time
- create separate component for button only

It will be more visible then that basing on selection we have different buttons

2024-10-21 10:38 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/sort-filter/sort-filter.component.tsx
> +    document.addEventListener('mousedown', handleClickOutside);
1. why it is different? why do we have both?
2. can we create different versions of the same component (in design system)?

2024-10-21 10:38 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/history/use-history-data.hook.ts
> +      const newResults = data.results.filter(
I'm not asking about the task. You know that in the future we will implement websockets so implementation should support it from start. If you don't do this then we will have to rewrite implementation. You should think about the whole implementation (websockets, possible future changes, will we need BE statuses in the future, etc). Then create solution which support all of it, eg while implementing websockets we should only update status somewhere. We shouldn't be forced to rewrite current implementetion every time requirements change a little bit

2024-10-21 10:38 UTC, mlu-ssoft commented on libs/map/feature-action-creator-panel/src/lib/content/presets/presets.component.tsx
> +  if (isPending || isFetching) {
if you will use `isLoading` only then you won't see spinner twice (request sill will be made, but data from cache will be displayed to the user and replaced under the hood when call is finished)

2024-10-21 12:07 UTC, KatarzynaPaszko commented on libs/map/feature-action-creator-panel/src/lib/content/history/sort-filter/sort-filter.component.tsx
> +    document.addEventListener('mousedown', handleClickOutside);
As discussed on call, it is different visually and with logic. 

I have extracted document.addEventListener mouse down logic to separate hook `useOutsideClick`

2024-10-21 12:53 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/history/history.model.ts
> +    .transform((dateString) => {
I don't know, for now nowhere, but in the future we may use it somewhere else. We shouldn't be forced to change implementation every time we will be adding new feature. Data access layer can be used by multiple views and it should be treatten like that (one to many relationship). For now it is just one view, but in the future we might have features which will use this data too. It is cached data so you should just take it and do something in the view (if needed). The same applies to statuses: will we need BE statuses in different places in the future? If we will have different view (something similar to history tab), what is the chance that we will have exact same statuses as they are currently are in history tab? Where is better to do mapping (in data-access layer or in the component itself)? Those are questions that should be asked/answered. So you should cover not only this exaclt implelmentation but create code which will allow us to easilly extend/add new functionalities without needing of refactor/change current ones

2024-10-21 12:55 UTC, mlu-ssoft commented on libs/map/data-access-map/src/lib/history/history.query.tsx
> +const history = async ({
yep, you can change it also there

2024-10-22 07:24 UTC, mlu-ssoft approved these changes

2024-10-22 07:24 UTC, mlu-ssoft commented on libs/shared/utils/date/src/lib/date.utils.ts
> +    case 'DD-MM-YY': {
shouldn't it be DD/MM/YYYY? I added it in another PR

2024-10-22 07:38 UTC, KatarzynaPaszko commented on libs/shared/utils/date/src/lib/date.utils.ts
> +    case 'DD-MM-YY': {
I added it as per design:
<img width="372" alt="Screenshot 2024-10-22 at 09 38 01" src="https://github.com/user-attachments/assets/26b114cf-f531-41a6-a34f-114eb26cf838">

2024-10-22 08:56 UTC, merged